### ISSUE TITLE
Kibana kan ikke beregne det toale antal hentede objekter

### ISSUE THREAD

**Issue by petergarnaes** [DBCDK/OpenSearch-webservice#8]
Vi vil gerne kunne plotte antal hentede objekter sammen med tiden for de langsomme kald i Kibana.

Kibana (og vist heller ikke ElasticSearch) er ikke i stand til at summere felter fra samme log-linje, så hvis vi skal plotte antallet af objekter der hentes, skal de ligges sammen i ét felt. Dvs. vi skal bruge noget alla `repoRecs` + `repoCache` i et separat felt, måske `repoTotal`?

**Comment by fvsdbc** [comment]
Udvidet til at indeholde repoTotal som foreslået. En del af version 5.1.
